# config/robots/aka00v4-rock4d.yaml
# AKA-00V4-ROCK4D开发板特定配置
# 共有配置见 aka00v4-common.yaml

HARDWARE:
  MODE: "rk3576"
  MODEL_FORMAT: "rknn"
  BASE:
    PORT: "/dev/ttyACM0"
  ARM:
    PORT: "/dev/ttyS2"

VISION:
  MODEL_NAME: "yolov8n-int8-tennis.rknn"