# config/robots/aka00v4-rk3588.yaml
# AKA-00V4-RK3588开发板特定配置
# 共有配置见 aka00v4-common.yaml

HARDWARE:
  MODE: "rk3588"
  MODEL_FORMAT: "rknn"
  BASE:
    PORT: "/dev/ttyS6"
  ARM:
    PORT: "/dev/ttyS3"

VISION:
  MODEL_NAME: "yolov8n-fp16-tennis.rknn"