# config/robots/aka00v4-k3.yaml
# AKA-00V4-K3开发板特定配置
# 共有配置见 aka00v4-common.yaml

HARDWARE:
  MODE: "k3"
  MODEL_FORMAT: "rknn"
  BASE:
    PORT: "/dev/ttyACM0"
  ARM:
    PORT: "/dev/ttyUSB0"

VISION:
  MODEL_NAME: "yolov8n-int8-tennis.rknn"