# config/robots/aka00v4-lubancat3.yaml
# AKA-00V4-LUBANCAT3开发板特定配置
# 共有配置见 aka00v4-common.yaml

HARDWARE:
  MODE: "rk3576"
  MODEL_FORMAT: "rknn"
  BASE:
    PORT: "/dev/ttyS3"
  ARM:
    PORT: "/dev/ttyS10"

VISION:
  MODEL_NAME: "yolov8n-int8-tennis.rknn"